// List of countries with their codes and phone codes
export interface Country {
  name: string;
  code: string; // ISO country code (e.g., 'US', 'PK', 'IN')
  phoneCode: string; // Phone country code (e.g., '+1', '+92', '+91')
}

export const COUNTRIES: Country[] = [
  { name: 'United States', code: 'US', phoneCode: '+1' },
  { name: 'United Kingdom', code: 'GB', phoneCode: '+44' },
  { name: 'Canada', code: 'CA', phoneCode: '+1' },
  { name: 'Australia', code: 'AU', phoneCode: '+61' },
  { name: 'Germany', code: 'DE', phoneCode: '+49' },
  { name: 'France', code: 'FR', phoneCode: '+33' },
  { name: 'Italy', code: 'IT', phoneCode: '+39' },
  { name: 'Spain', code: 'ES', phoneCode: '+34' },
  { name: 'Netherlands', code: 'NL', phoneCode: '+31' },
  { name: 'Belgium', code: 'BE', phoneCode: '+32' },
  { name: 'Switzerland', code: 'CH', phoneCode: '+41' },
  { name: 'Austria', code: 'AT', phoneCode: '+43' },
  { name: 'Sweden', code: 'SE', phoneCode: '+46' },
  { name: 'Norway', code: 'NO', phoneCode: '+47' },
  { name: 'Denmark', code: 'DK', phoneCode: '+45' },
  { name: 'Finland', code: 'FI', phoneCode: '+358' },
  { name: 'Poland', code: 'PL', phoneCode: '+48' },
  { name: 'Portugal', code: 'PT', phoneCode: '+351' },
  { name: 'Greece', code: 'GR', phoneCode: '+30' },
  { name: 'Ireland', code: 'IE', phoneCode: '+353' },
  { name: 'Pakistan', code: 'PK', phoneCode: '+92' },
  { name: 'India', code: 'IN', phoneCode: '+91' },
  { name: 'Bangladesh', code: 'BD', phoneCode: '+880' },
  { name: 'Sri Lanka', code: 'LK', phoneCode: '+94' },
  { name: 'Nepal', code: 'NP', phoneCode: '+977' },
  { name: 'Afghanistan', code: 'AF', phoneCode: '+93' },
  { name: 'China', code: 'CN', phoneCode: '+86' },
  { name: 'Japan', code: 'JP', phoneCode: '+81' },
  { name: 'South Korea', code: 'KR', phoneCode: '+82' },
  { name: 'Singapore', code: 'SG', phoneCode: '+65' },
  { name: 'Malaysia', code: 'MY', phoneCode: '+60' },
  { name: 'Thailand', code: 'TH', phoneCode: '+66' },
  { name: 'Indonesia', code: 'ID', phoneCode: '+62' },
  { name: 'Philippines', code: 'PH', phoneCode: '+63' },
  { name: 'Vietnam', code: 'VN', phoneCode: '+84' },
  { name: 'United Arab Emirates', code: 'AE', phoneCode: '+971' },
  { name: 'Saudi Arabia', code: 'SA', phoneCode: '+966' },
  { name: 'Qatar', code: 'QA', phoneCode: '+974' },
  { name: 'Kuwait', code: 'KW', phoneCode: '+965' },
  { name: 'Bahrain', code: 'BH', phoneCode: '+973' },
  { name: 'Oman', code: 'OM', phoneCode: '+968' },
  { name: 'Israel', code: 'IL', phoneCode: '+972' },
  { name: 'Turkey', code: 'TR', phoneCode: '+90' },
  { name: 'Egypt', code: 'EG', phoneCode: '+20' },
  { name: 'South Africa', code: 'ZA', phoneCode: '+27' },
  { name: 'Nigeria', code: 'NG', phoneCode: '+234' },
  { name: 'Kenya', code: 'KE', phoneCode: '+254' },
  { name: 'Brazil', code: 'BR', phoneCode: '+55' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54' },
  { name: 'Mexico', code: 'MX', phoneCode: '+52' },
  { name: 'Chile', code: 'CL', phoneCode: '+56' },
  { name: 'Colombia', code: 'CO', phoneCode: '+57' },
  { name: 'Peru', code: 'PE', phoneCode: '+51' },
  { name: 'Venezuela', code: 'VE', phoneCode: '+58' },
  { name: 'New Zealand', code: 'NZ', phoneCode: '+64' },
  { name: 'Russia', code: 'RU', phoneCode: '+7' },
  { name: 'Ukraine', code: 'UA', phoneCode: '+380' },
  { name: 'Romania', code: 'RO', phoneCode: '+40' },
  { name: 'Czech Republic', code: 'CZ', phoneCode: '+420' },
  { name: 'Hungary', code: 'HU', phoneCode: '+36' },
  { name: 'Croatia', code: 'HR', phoneCode: '+385' },
  { name: 'Bulgaria', code: 'BG', phoneCode: '+359' },
  { name: 'Serbia', code: 'RS', phoneCode: '+381' },
  { name: 'Slovakia', code: 'SK', phoneCode: '+421' },
  { name: 'Slovenia', code: 'SI', phoneCode: '+386' },
  { name: 'Lithuania', code: 'LT', phoneCode: '+370' },
  { name: 'Latvia', code: 'LV', phoneCode: '+371' },
  { name: 'Estonia', code: 'EE', phoneCode: '+372' },
].sort((a, b) => a.name.localeCompare(b.name));

// Helper function to get country by code
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((country) => country.code === code);
}

// Helper function to get country by phone code
export function getCountryByPhoneCode(phoneCode: string): Country | undefined {
  return COUNTRIES.find((country) => country.phoneCode === phoneCode);
}

// Cities data by country code
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  'US': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'San Francisco', 'Columbus', 'Fort Worth', 'Charlotte', 'Seattle', 'Denver', 'Washington', 'Boston', 'El Paso', 'Detroit', 'Nashville', 'Portland', 'Oklahoma City', 'Las Vegas', 'Memphis', 'Louisville', 'Baltimore', 'Milwaukee'],
  'PK': ['Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 'Rawalpindi', 'Multan', 'Gujranwala', 'Hyderabad', 'Peshawar', 'Quetta', 'Sargodha', 'Sialkot', 'Bahawalpur', 'Sukkur', 'Jhang', 'Sheikhupura', 'Larkana', 'Gujrat', 'Kasur', 'Rahim Yar Khan', 'Sahiwal', 'Okara', 'Mingora', 'Nawabshah', 'Chiniot', 'Kotri', 'Khanpur', 'Hafizabad', 'Kohat', 'Jacobabad'],
  'IN': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Ahmedabad', 'Chennai', 'Kolkata', 'Surat', 'Pune', 'Jaipur', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Thane', 'Bhopal', 'Visakhapatnam', 'Patna', 'Vadodara', 'Ghaziabad', 'Ludhiana', 'Agra', 'Nashik', 'Faridabad', 'Meerut', 'Rajkot', 'Varanasi', 'Srinagar', 'Amritsar', 'Chandigarh'],
  'GB': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Liverpool', 'Leeds', 'Sheffield', 'Edinburgh', 'Bristol', 'Cardiff', 'Belfast', 'Newcastle', 'Nottingham', 'Leicester', 'Coventry', 'Bradford', 'Sunderland', 'Brighton', 'Hull', 'Plymouth', 'Stoke-on-Trent', 'Wolverhampton', 'Derby', 'Southampton', 'Swansea', 'Salford', 'Aberdeen', 'Westminster', 'Portsmouth', 'York'],
  'CA': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Kitchener', 'London', 'Victoria', 'Halifax', 'Oshawa', 'Windsor', 'Saskatoon', 'Regina', 'Sherbrooke', 'Kelowna', 'Barrie', 'Abbotsford', 'Sudbury', 'Kingston', 'Saguenay', 'Trois-Rivières', 'Guelph', 'Cambridge', 'Thunder Bay', 'Saint John', 'Moncton'],
  'AU': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Newcastle', 'Canberra', 'Sunshine Coast', 'Wollongong', 'Hobart', 'Geelong', 'Townsville', 'Cairns', 'Toowoomba', 'Darwin', 'Ballarat', 'Bendigo', 'Albury', 'Launceston', 'Mackay', 'Rockhampton', 'Bunbury', 'Bundaberg', 'Coffs Harbour', 'Wagga Wagga', 'Hervey Bay', 'Port Macquarie', 'Shepparton', 'Gladstone'],
  'AE': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Khor Fakkan', 'Kalba', 'Jebel Ali', 'Madinat Zayed', 'Ruwais', 'Ghantoot', 'Liwa Oasis', 'Al Dhafra', 'Ar-Rams', 'Dibba Al-Fujairah', 'Dibba Al-Hisn', 'Hatta'],
  'SA': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Taif', 'Abha', 'Tabuk', 'Buraidah', 'Khamis Mushait', 'Hail', 'Hafr Al-Batin', 'Jubail', 'Al-Kharj', 'Najran', 'Al Qatif', 'Yanbu', 'Arar', 'Sakaka'],
  'DE': ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Essen', 'Leipzig', 'Bremen', 'Dresden', 'Hannover', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Münster'],
  'FR': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Saint-Étienne', 'Toulon', 'Grenoble', 'Dijon', 'Angers', 'Nîmes', 'Villeurbanne'],
  'IT': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Bari', 'Catania', 'Venice', 'Verona', 'Messina', 'Padua', 'Trieste', 'Brescia', 'Parma', 'Taranto', 'Prato', 'Modena'],
  'ES': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma', 'Las Palmas', 'Bilbao', 'Alicante', 'Córdoba', 'Valladolid', 'Vigo', 'Gijón', 'Hospitalet', 'Granada', 'Vitoria', 'A Coruña', 'Elche'],
  'CN': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi\'an', 'Nanjing', 'Tianjin', 'Suzhou', 'Chongqing', 'Dongguan', 'Foshan', 'Jinan', 'Hefei', 'Dalian', 'Fuzhou', 'Xiamen', 'Kunming'],
  'JP': ['Tokyo', 'Yokohama', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka', 'Kobe', 'Kawasaki', 'Kyoto', 'Saitama', 'Hiroshima', 'Sendai', 'Chiba', 'Kitakyushu', 'Sakai', 'Niigata', 'Hamamatsu', 'Shizuoka', 'Okayama', 'Kumamoto'],
  'KR': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Goyang', 'Seongnam', 'Bucheon', 'Ansan', 'Anyang', 'Jeonju', 'Cheonan', 'Namyangju', 'Hwaseong', 'Gimhae', 'Pyeongtaek'],
  'SG': ['Singapore'],
  'MY': ['Kuala Lumpur', 'George Town', 'Ipoh', 'Johor Bahru', 'Melaka', 'Kota Kinabalu', 'Kuching', 'Shah Alam', 'Klang', 'Kota Bharu', 'Seremban', 'Sandakan', 'Kuantan', 'Tawau', 'Miri', 'Alor Setar', 'Sibu', 'Kulim', 'Taiping', 'Bintulu'],
  'TH': ['Bangkok', 'Nonthaburi', 'Nakhon Ratchasima', 'Chiang Mai', 'Hat Yai', 'Udon Thani', 'Pak Kret', 'Khon Kaen', 'Chaophraya Surasak', 'Nakhon Si Thammarat', 'Phuket', 'Pattaya', 'Nakhon Pathom', 'Lampang', 'Rayong', 'Phitsanulok', 'Songkhla', 'Yala', 'Chon Buri', 'Sakon Nakhon'],
  'ID': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang', 'Depok', 'Tangerang', 'South Tangerang', 'Bekasi', 'Batam', 'Bogor', 'Pekanbaru', 'Bandar Lampung', 'Padang', 'Malang', 'Denpasar', 'Samarinda', 'Tasikmalaya'],
  'PH': ['Manila', 'Quezon City', 'Caloocan', 'Davao City', 'Cebu City', 'Zamboanga City', 'Antipolo', 'Pasig', 'Taguig', 'Cagayan de Oro', 'Parañaque', 'Dasmariñas', 'Valenzuela', 'Las Piñas', 'Makati', 'Bacolod', 'Bacoor', 'General Santos', 'Muntinlupa', 'San Jose del Monte'],
  'VN': ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Haiphong', 'Can Tho', 'Bien Hoa', 'Nha Trang', 'Hue', 'Vung Tau', 'Quy Nhon', 'Rach Gia', 'Long Xuyen', 'Buon Ma Thuot', 'Cam Ranh', 'Thai Nguyen', 'Pleiku', 'My Tho', 'Soc Trang', 'Bac Lieu', 'Ca Mau'],
  'TR': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Gaziantep', 'Konya', 'Kayseri', 'Mersin', 'Eskisehir', 'Diyarbakir', 'Samsun', 'Denizli', 'Sanliurfa', 'Adapazari', 'Malatya', 'Kahramanmaras', 'Erzurum', 'Van'],
  'EG': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Aswan', 'Asyut', 'Ismailia', 'Faiyum', 'Zagazig', 'Damietta', 'Aswan', 'Minya', 'Damanhur', 'Beni Suef', 'Qena', 'Sohag', 'Hurghada'],
  'ZA': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Pietermaritzburg', 'Benoni', 'Tembisa', 'East London', 'Vereeniging', 'Bloemfontein', 'Soweto', 'Boksburg', 'Welkom', 'Klerksdorp', 'Potchefstroom', 'Rustenburg', 'Nelspruit', 'Kimberley', 'Polokwane'],
  'BR': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belém', 'Goiânia', 'Guarulhos', 'Campinas', 'São Luís', 'São Gonçalo', 'Maceió', 'Duque de Caxias', 'Natal', 'Teresina'],
  'MX': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'León', 'Juárez', 'Torreón', 'Querétaro', 'San Luis Potosí', 'Mérida', 'Mexicali', 'Aguascalientes', 'Tampico', 'Culiacán', 'Cuernavaca', 'Acapulco', 'Toluca', 'Morelia', 'Chihuahua'],
  'AR': ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán', 'La Plata', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan', 'Resistencia', 'Santiago del Estero', 'Corrientes', 'Posadas', 'San Salvador de Jujuy', 'Bahía Blanca', 'Paraná', 'Neuquén', 'Formosa', 'San Luis'],
  'RU': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Omsk', 'Rostov-on-Don', 'Ufa', 'Krasnoyarsk', 'Voronezh', 'Perm', 'Volgograd', 'Krasnodar', 'Saratov', 'Tyumen', 'Tolyatti', 'Izhevsk'],
  'NL': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Groningen', 'Tilburg', 'Almere', 'Breda', 'Nijmegen', 'Enschede', 'Haarlem', 'Arnhem', 'Zaanstad', 'Amersfoort', 'Apeldoorn', 'Hoofddorp', 'Maastricht', 'Leiden', 'Dordrecht'],
  'BE': ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liège', 'Bruges', 'Namur', 'Leuven', 'Mons', 'Aalst', 'Mechelen', 'Kortrijk', 'Ostend', 'Hasselt', 'Sint-Niklaas', 'Tournai', 'Genk', 'Seraing', 'Roeselare', 'Verviers'],
  'CH': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel', 'Thun', 'Köniz', 'La Chaux-de-Fonds', 'Schaffhausen', 'Fribourg', 'Chur', 'Neuchâtel', 'Vernier', 'Uster', 'Sion'],
  'AT': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Pölten', 'Dornbirn', 'Steyr', 'Wiener Neustadt', 'Feldkirch', 'Bregenz', 'Leonding', 'Klosterneuburg', 'Baden', 'Wolfsberg', 'Leoben', 'Krems'],
  'SE': ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås', 'Örebro', 'Linköping', 'Helsingborg', 'Jönköping', 'Norrköping', 'Lund', 'Umeå', 'Gävle', 'Borås', 'Södertälje', 'Eskilstuna', 'Karlstad', 'Halmstad', 'Växjö', 'Sundsvall'],
  'NO': ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Bærum', 'Kristiansand', 'Fredrikstad', 'Sandnes', 'Tromsø', 'Sarpsborg', 'Skien', 'Ålesund', 'Sandefjord', 'Haugesund', 'Tønsberg', 'Arendal', 'Moss', 'Hamar', 'Steinkjer', 'Bodø'],
  'DK': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle', 'Roskilde', 'Herning', 'Helsingør', 'Silkeborg', 'Næstved', 'Fredericia', 'Viborg', 'Køge', 'Holstebro', 'Taastrup', 'Sønderborg'],
  'FI': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyväskylä', 'Lahti', 'Kuopio', 'Pori', 'Kouvola', 'Joensuu', 'Lappeenranta', 'Hämeenlinna', 'Vaasa', 'Seinäjoki', 'Rovaniemi', 'Mikkeli', 'Kotka', 'Salo'],
  'PL': ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań', 'Gdańsk', 'Szczecin', 'Bydgoszcz', 'Lublin', 'Katowice', 'Białystok', 'Gdynia', 'Częstochowa', 'Radom', 'Sosnowiec', 'Toruń', 'Kielce', 'Gliwice', 'Zabrze', 'Bytom'],
  'PT': ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora', 'Braga', 'Funchal', 'Coimbra', 'Setúbal', 'Almada', 'Agualva-Cacém', 'Queluz', 'Rio de Mouro', 'Barreiro', 'Aveiro', 'Évora', 'Faro', 'Leiria', 'Viseu', 'Guimarães', 'Santarém'],
  'GR': ['Athens', 'Thessaloniki', 'Patras', 'Piraeus', 'Larissa', 'Heraklion', 'Peristeri', 'Kallithea', 'Acharnes', 'Kalamaria', 'Nikaia', 'Glyfada', 'Volos', 'Ilio', 'Ilioupoli', 'Keratsini', 'Evosmos', 'Chalandri', 'Nea Smyrni', 'Marousi'],
  'IE': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan', 'Ennis', 'Kilkenny', 'Carlow', 'Tralee', 'Newbridge', 'Naas', 'Athlone', 'Portlaoise', 'Mullingar', 'Celbridge'],
  'BD': ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet', 'Barisal', 'Rangpur', 'Comilla', 'Narayanganj', 'Gazipur', 'Jessore', 'Cox\'s Bazar', 'Bogra', 'Dinajpur', 'Mymensingh', 'Tangail', 'Jamalpur', 'Pabna', 'Saidpur', 'Noakhali'],
  'LK': ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo', 'Trincomalee', 'Batticaloa', 'Anuradhapura', 'Ratnapura', 'Kalutara', 'Matara', 'Kurunegala', 'Badulla', 'Gampaha', 'Chilaw', 'Panadura', 'Moratuwa', 'Kegalle', 'Nuwara Eliya', 'Polonnaruwa'],
  'NP': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Biratnagar', 'Birgunj', 'Dharan', 'Butwal', 'Hetauda', 'Nepalgunj', 'Itahari', 'Dhading', 'Janakpur', 'Dhangadhi', 'Tulsipur', 'Bhimdatta', 'Siddharthanagar', 'Gulariya', 'Rajbiraj', 'Lahan'],
  'AF': ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Kunduz', 'Jalalabad', 'Ghazni', 'Balkh', 'Baghlan', 'Gardez', 'Farah', 'Ghazni', 'Khost', 'Lashkar Gah', 'Taloqan', 'Sheberghan', 'Sar-e Pol', 'Zaranj', 'Chaghcharan', 'Fayzabad'],
  'QA': ['Doha', 'Al Rayyan', 'Umm Salal', 'Al Wakrah', 'Al Khor', 'Dukhan', 'Al Shamal', 'Madinat ash Shamal', 'Al Daayen', 'Al Sheehaniya'],
  'KW': ['Kuwait City', 'Al Ahmadi', 'Hawalli', 'Al Jahra', 'Farwaniya', 'Mubarak Al-Kabeer', 'Al Asimah', 'Ahmadi', 'Jahra', 'Farwaniyah'],
  'BH': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'A\'ali', 'Isa Town', 'Sitra', 'Budaiya', 'Jidhafs', 'Adliya'],
  'OM': ['Muscat', 'Seeb', 'Salalah', 'Bawshar', 'Sohar', 'Rustaq', 'Sur', 'Ibri', 'Saham', 'Barka'],
  'IL': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beer Sheva', 'Bnei Brak', 'Holon', 'Bat Yam', 'Ramat Gan', 'Rehovot', 'Ashkelon', 'Herzliya', 'Kfar Saba', 'Hadera', 'Modiin', 'Lod', 'Nazareth'],
  'NG': ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Kaduna', 'Maiduguri', 'Zaria', 'Aba', 'Jos', 'Ilorin', 'Ile-Ife', 'Onitsha', 'Abeokuta', 'Enugu', 'Warri', 'Calabar', 'Uyo', 'Akure'],
  'KE': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Kitale', 'Garissa', 'Kakamega', 'Kisii', 'Meru', 'Nyeri', 'Machakos', 'Embu', 'Narok', 'Kericho', 'Bungoma', 'Busia', 'Homa Bay'],
  'NZ': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Napier', 'Palmerston North', 'Dunedin', 'Rotorua', 'New Plymouth', 'Whangarei', 'Invercargill', 'Nelson', 'Hastings', 'Gisborne', 'Timaru', 'Blenheim', 'Taupo', 'Pukekohe', 'Masterton'],
  'CL': ['Santiago', 'Valparaíso', 'Concepción', 'La Serena', 'Antofagasta', 'Temuco', 'Rancagua', 'Talca', 'Arica', 'Iquique', 'Puerto Montt', 'Los Angeles', 'Calama', 'Coquimbo', 'Valdivia', 'Osorno', 'Curicó', 'Quilpué', 'Copiapó', 'Linares'],
  'CO': ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena', 'Cúcuta', 'Soledad', 'Ibagué', 'Bucaramanga', 'Santa Marta', 'Pereira', 'Villavicencio', 'Bello', 'Pasto', 'Valledupar', 'Montería', 'Manizales', 'Neiva', 'Armenia', 'Sincelejo'],
  'PE': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco', 'Chimbote', 'Huancayo', 'Tacna', 'Ica', 'Juliaca', 'Sullana', 'Chincha Alta', 'Ayacucho', 'Cajamarca', 'Pucallpa', 'Tumbes', 'Talara', 'Huaraz'],
  'VE': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana', 'Barcelona', 'Maturín', 'Ciudad Bolívar', 'San Cristóbal', 'Cumaná', 'Barinas', 'Mérida', 'Cabimas', 'Puerto La Cruz', 'Punto Fijo', 'Guanare', 'Acarigua', 'Carúpano', 'Valera'],
  'RO': ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov', 'Galați', 'Ploiești', 'Oradea', 'Brăila', 'Arad', 'Pitești', 'Sibiu', 'Bacău', 'Târgu Mureș', 'Baia Mare', 'Buzău', 'Botoșani', 'Satu Mare'],
  'CZ': ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc', 'Ústí nad Labem', 'České Budějovice', 'Hradec Králové', 'Pardubice', 'Zlín', 'Havířov', 'Kladno', 'Most', 'Opava', 'Frýdek-Místek', 'Karviná', 'Jihlava', 'Teplice', 'Chomutov'],
  'HU': ['Budapest', 'Debrecen', 'Szeged', 'Miskolc', 'Pécs', 'Győr', 'Nyíregyháza', 'Kecskemét', 'Székesfehérvár', 'Szombathely', 'Szolnok', 'Tatabánya', 'Kaposvár', 'Békéscaba', 'Zalaegerszeg', 'Érd', 'Sopron', 'Veszprém', 'Baja', 'Dunaújváros'],
  'HR': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Slavonski Brod', 'Pula', 'Sesvete', 'Karlovac', 'Varaždin', 'Šibenik', 'Dubrovnik', 'Bjelovar', 'Sisak', 'Velika Gorica', 'Vinkovci', 'Koprivnica', 'Čakovec', 'Požega', 'Solin'],
  'BG': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobrich', 'Shumen', 'Pernik', 'Haskovo', 'Yambol', 'Pazardzhik', 'Blagoevgrad', 'Veliko Tarnovo', 'Vratsa', 'Gabrovo', 'Asenovgrad', 'Kardzhali'],
  'RS': ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pančevo', 'Čačak', 'Novi Pazar', 'Kraljevo', 'Smederevo', 'Leskovac', 'Užice', 'Vranje', 'Šabac', 'Sombor', 'Požarevac', 'Pirot', 'Zaječar', 'Jagodina'],
  'SK': ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Banská Bystrica', 'Nitra', 'Trnava', 'Trenčín', 'Martin', 'Poprad', 'Prievidza', 'Zvolen', 'Považská Bystrica', 'Michalovce', 'Nové Zámky', 'Spišská Nová Ves', 'Komárno', 'Humenné', 'Levice', 'Bardejov'],
  'SI': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Velenje', 'Koper', 'Novo Mesto', 'Ptuj', 'Trbovlje', 'Kamnik', 'Jesenice', 'Nova Gorica', 'Murska Sobota', 'Škofja Loka', 'Domžale', 'Izola', 'Kočevje', 'Postojna', 'Logatec', 'Slovenj Gradec'],
  'LT': ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys', 'Alytus', 'Marijampolė', 'Mazeikiai', 'Jonava', 'Utena', 'Kėdainiai', 'Tauragė', 'Telšiai', 'Visaginas', 'Plungė', 'Kretinga', 'Radviliškis', 'Druskininkai', 'Palanga', 'Rokiškis'],
  'LV': ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils', 'Rēzekne', 'Valmiera', 'Jēkabpils', 'Ogre', 'Tukums', 'Cēsis', 'Salaspils', 'Kuldīga', 'Olaine', 'Saldus', 'Talsi', 'Dobele', 'Krāslava', 'Bauska'],
  'EE': ['Tallinn', 'Tartu', 'Narva', 'Pärnu', 'Kohtla-Järve', 'Viljandi', 'Rakvere', 'Maardu', 'Kuressaare', 'Sillamäe', 'Valga', 'Võru', 'Jõhvi', 'Haapsalu', 'Keila', 'Paide', 'Tapa', 'Põlva', 'Kiviõli', 'Elva'],
};

// Helper function to get cities by country code
export function getCitiesByCountryCode(countryCode: string): string[] {
  return CITIES_BY_COUNTRY[countryCode] || [];
}
