/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/activities` | `/onboarding/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/expertise` | `/onboarding/expertise`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/personal-info` | `/onboarding/personal-info`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/welcome-1` | `/onboarding/welcome-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/welcome-2` | `/onboarding/welcome-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding/activities` | `/onboarding/activities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding/expertise` | `/onboarding/expertise`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding/personal-info` | `/onboarding/personal-info`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding/welcome-1` | `/onboarding/welcome-1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding/welcome-2` | `/onboarding/welcome-2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-in${`?${string}` | `#${string}` | ''}` | `/sign-in${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/sign-up${`?${string}` | `#${string}` | ''}` | `/sign-up${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding/activities${`?${string}` | `#${string}` | ''}` | `/onboarding/activities${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding/expertise${`?${string}` | `#${string}` | ''}` | `/onboarding/expertise${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding/personal-info${`?${string}` | `#${string}` | ''}` | `/onboarding/personal-info${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding/welcome-1${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome-1${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding/welcome-2${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome-2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-in` | `/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/sign-up` | `/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/activities` | `/onboarding/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/expertise` | `/onboarding/expertise`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/personal-info` | `/onboarding/personal-info`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/welcome-1` | `/onboarding/welcome-1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding/welcome-2` | `/onboarding/welcome-2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
